import { ScoreBadge } from './ScoreBadge';
import { ArrowRight } from 'lucide-react';

interface ResultCardProps {
  result: {
    score: number;
    summary: string;
    nextStep: string;
    strengths: string[];
    risks: string[];
  };
  hasSelectedJob: boolean;
}

export function ResultCard({ result, hasSelectedJob }: ResultCardProps) {
  const handleAddToPipeline = () => {
    // Mock action
    alert('Candidate added to ATS pipeline');
  };

  return (
    <div className="bg-white border border-slate-200 rounded-2xl p-8 shadow-sm">
      {/* Header */}
      <div className="flex items-start justify-between mb-8 pb-6 border-b border-slate-100">
        <div>
          <h2 className="text-slate-900 mb-1">AI Match Result</h2>
          <p className="text-slate-500">Generated by Intime AI using your JD + candidate data.</p>
        </div>
        <ScoreBadge score={result.score} />
      </div>

      {/* Summary + Suggested Next Step */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8 pb-8 border-b border-slate-100">
        {/* Summary - 2/3 width */}
        <div className="md:col-span-2">
          <h3 className="text-slate-900 mb-3">Summary</h3>
          <p className="text-slate-700 leading-relaxed">{result.summary}</p>
        </div>
        
        {/* Suggested Next Step - 1/3 width */}
        <div className="bg-indigo-50/50 border border-indigo-100 rounded-xl p-5">
          <h3 className="text-slate-900 mb-3">Suggested Next Step</h3>
          <p className="text-slate-700 leading-relaxed">{result.nextStep}</p>
        </div>
      </div>

      {/* Strengths / Risks - Balanced Split */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8 pb-8 border-b border-slate-100">
        {/* Strengths */}
        <div>
          <h3 className="text-slate-900 mb-4">Top Strengths</h3>
          <ul className="space-y-3">
            {result.strengths.map((strength, index) => (
              <li key={index} className="flex gap-3">
                <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-emerald-500 flex-shrink-0" />
                <span className="text-slate-700 leading-relaxed">{strength}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Risks */}
        <div>
          <h3 className="text-slate-900 mb-4">Gaps & Risks</h3>
          <ul className="space-y-3">
            {result.risks.map((risk, index) => (
              <li key={index} className="flex gap-3">
                <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-amber-500 flex-shrink-0" />
                <span className="text-slate-700 leading-relaxed">{risk}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Add to Pipeline CTA */}
      <div className="flex justify-center">
        <button
          onClick={handleAddToPipeline}
          className="flex items-center gap-2 px-6 py-2.5 bg-white border border-slate-200 rounded-lg hover:border-slate-300 hover:bg-slate-50 transition-all text-slate-700"
        >
          <span>Add Candidate to Pipeline</span>
          <ArrowRight className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
}
